### PR TITLE
Add Two Additional CMS Github Orgs to Metrics Site as Well as Merge with Dev for Stability

### PR DESCRIPTION
**Pull request by IsaacMilarky**
## Problem

A goal of the metrics website is to grow in its capacity to show metrics about a large breadth of the CMS open source ecosystem.

## Solution

Now, both [Enterprise-CMCS](https://github.com/orgs/Enterprise-CMCS) and [CMS-Enterprise](https://github.com/CMS-Enterprise) were added to the tracked orgs and repos for the metrics website. Also, a hot-fix is included to fix a urgent error that occurred when a repository doesn't set a default git branch. 

## Result

More repositories and orgs will be added to the metrics website. 

Screenshot 2024-01-22 at 6 56 57 PM

### CODE REVIEW

**Review by natalialuzuriaga — APPROVED** [review]
LGTM 👍  Was able to get this running locally on my end and website includes the 2 new orgs

**Comment by natalialuzuriaga** [comment]
Flagging for the future that the org GH API metrics look off (all values are 0) and running ./update.sh runs to an error during graph generation. We can address this later

**Comment by IsaacMilarky** [comment]
> Flagging for the future that the org GH API metrics look off (latest values are the same across all orgs) and running ./update.sh runs to an error during graph generation. We can address this later

Oh yeah good catch. I fixed this in dev but the bug is still in main. Will push a commit to fix

**Comment by IsaacMilarky** [comment]
I ended up merging with `dev` since it became apparent that it was too far ahead of main to easily apply the bug-fixes from it to this PR without a full merge. @natalialuzuriaga

**Review by natalialuzuriaga — APPROVED** [review]
LGTM 🚀  Verified that the website is working correctly with all the changes from dev. I see that the org bug is also fixed 👍

**Pull request merged**
