### PR TITLE
Update Backend Docs

### PR DESCRIPTION
**Pull request by IsaacMilarky**
## Problem

Previous documentation regarding the back-end was very out of date. 

## Solution

Update the documentation

## Result

Moved all previous documentation to the docs directory and updated them to reflect the current code. 

# New UML:
UML_Metrics_Diagram

### CODE REVIEW

**Review by natalialuzuriaga — CHANGES_REQUESTED** [review]
Love it! Could you add these links to these new docs in the Documentation Index section of the README

**Comment by natalialuzuriaga** [comment]
and also reference it in the Documentation section in CONTRIBUTING

**Comment by IsaacMilarky** [comment]
Made requested change @natalialuzuriaga

**Review by natalialuzuriaga — APPROVED** [review]
LGTM 👍

**Pull request merged**
